main_packs = [
    {"Pack Name": "Swamps Of Famine", "Cards Per Pack": 7, "Price (Per Pack)": 1.50, "Cards In Set": 90, "Pack ID": "SWOF"},
    {"Pack Name": "Invasion Aggression", "Cards Per Pack": 7, "Price (Per Pack)": 2, "Cards In Set": 72, "Pack ID": "INOA"},
    {"Pack Name": "King Of Violence", "Cards Per Pack": 3, "Price (Per Pack)": 3.5, "Cards In Set": 10, "Pack ID": "KOV"},
    {"Pack Name": "The Web Court", "Cards Per Pack": 7, "Price (Per Pack)": 2, "Cards In Set": 47, "Pack ID": "TWCO"},
]




deck_box = [
    {"Structure Deck Name": "Into The Darkwood", "Cards In Deck": 46, "Price": 10, "Deck ID": "ITDW"},
    {"Structure Deck Name": "U.A Power Game", "Cards In Deck": 40, "Price": 10, "Deck ID": "UAPG"},
]


ID_List = {
# SWOF contains the "Vurko", "Swampswarm", and the "of Wants"/"Eveland" archetypes. 90 cards total.
    "SWOF": ["Vurko Annex Predator | (Level 4, Effect, DARK/Aqua)", 
    "Vurko Corpsumer | (Level 4, Effect, DARK/Aqua)", 
    "Vurko Gobblin | (Level 3, Effect, DARK/Aqua)", 
    "Vurko Gorefeaster | (Level 6, Effect, DARK/Aqua)",
    "Vurko Ingestator | (Level 4, Effect, DARK/Aqua)", 
    "Vurko Omnivover | (Level 4, Effect, DARK/Aqua)", 
    "Vurko Pareater | (Level 3, Effect, DARK/Aqua)", 
    "Vurko Singer of Cosmic Horrors | (Level 1, Tuner/Effect, DARK/Aqua)",
    "Seed Planting from Twisted Realms | (Normal Spell)",
    "Sewer Lair of the Vurko | (Field Spell)", 
    "Vurko Accumulating Nightmares | (Cont. Spell)", 
    "Vurko Circle of Doom | (Quick-Play Spell)", 
    "Vurko Resurfacing | (Cont. Spell)", 
    "Vurko Chimaera | (Cont. Trap)", 
    "Vurko Feeding Cycle | (Cont. Trap)", 
    "Vurko Slime Pool | (Cont. Trap)", 
    "Vurko Devora | (Level 7, Fusion/Effect, DARK/Aqua)",
    "Vurko Slime Producer | (Level 4, Fusion/Effect, DARK/Aqua)", 
    "Vurko Swallow Water | (Level 7, Fusion/Effect, DARK/Aqua)",
    "Outer Entity of Vurko - Abh | (Rank 4, Xyz/Effect, DARK/Aqua)", 
    "Vurko Cosmic Muncher | (Link-3, Link/Effect, DARK/Aqua)",
    "Vurko Wolf Downer | (Link-2, Link/Effect, DARK/Aqua)", 
    "Swampswarm Amazoness Sisters | (Level 4, Tuner/Effect, EARTH/Aqua)", 
    "Swampswarm Basilisk | (Level 5, Effect, EARTH/Aqua)", 
    "Swampswarm Illmaiden | (Level 3, Tuner/Effect, EARTH/Aqua)", 
    "Swampswarm Looming Horror | (Level 4, Effect, EARTH/Aqua)", 
    "Swampswarm Nymph | (Level 1, Tuner/Effect, EARTH/Aqua)", 
    "Swampswarm Life Force | (Level 2, Tuner/Effect, EARTH/Aqua)", 
    "Swampswarm Toad | (Level 3, Effect, EARTH/Aqua)", 
    "Swampswarm Witch | (Level 2, Tuner/Effect, EARTH/Aqua)", 
    "Swampswarm Wyvern | (Level 5, Effect, EARTH/Aqua)", 
    "Ruthless Swampswarm | (Field Spell)", 
    "Swampswarm Entity Blessing | (Equip Spell)", 
    "Swampswarm Resurfacing | (Equip Spell)", 
    "Swampswarm Witches' Convenant | (Cont. Spell)", 
    "Swampswarm Witches' Curse | (Equip Spell)", 
    "Swampswarm Witches' Lure | (Equip Spell)", 
    "Vurko Slime Leakage | (Normal Spell)", 
    "Swampswarm Witches' Trickery | (Cont. Trap)", 
    "Vurko Swampswarm | (Counter Trap)", 
    "Swampswarm Dryad | (Link-1, Link/Tuner/Effect, EARTH/Aqua)", 
    "Swampswarm Shadow Priestess | (Link-2, Link/Tuner/Effect, EARTH/Aqua)", 
    "Swampswarm Banshee | (Link-2, Link/Tuner/Effect, EARTH/Aqua)", 
    "Swampswarm Moss Guardian | (Link-3, Link/Effect, EARTH/Aqua)", 
    "Swampswarm Giant of the Dark Woods | (Link-2, Link/Effect, EARTH/Aqua)", 
    "Swampswarm Graveleech | (Link-2, Link/Effect, EARTH/Aqua)", 
    "Swampswarm Vision of Winter | (Link-2, Link/Tuner/Effect, EARTH/Aqua)", 
    "Sentient Swampswarm | (Link-4, Link/Effect, EARTH/Aqua)", 
    "Swampswarm Moss Yeti | (Link-1, Link/Effect, EARTH/Aqua)", 
    "Binder of Wants | (Level 3, Effect, DARK/Fiend)", 
    "Discipliner of Wants | (Level 4, Effect, DARK/Fiend)", 
    "Eveland Caresser | (Level 2, Effect, EARTH/Plant)", 
    "Eveland Gentle Touch | (Level 2, Effect, EARTH/Plant)", 
    "Eveland Leniency | (Level 5, Effect, EARTH/Plant)", 
    "Eveland Mercy | (Level 4, Effect, EARTH/Plant)",
    "Eveland Reliever | (Level 3, Effect, EARTH/Plant)", 
    "Mistress of Wants | (Level 5, Effect, DARK/Fiend)", 
    "Perverter of Wants | (Level 3, Effect, DARK/Fiend)", 
    "Punisher of Wants | (Level 2, Effect, DARK/Fiend)", 
    "Queen of Wants | (Level 4, Effect, DARK/Fiend)",
    "Garden of H-Eden | (Field Spell)", 
    "Slave of Wants | (Equip Spell)",
    "Eviland of Wants | (Cont. Trap)",
    "Cage of Wants | (Link-2, Link/Effect, DARK/Fiend)",
    "Denier of Wants | (Link-2, Link/Effect, DARK/Fiend)",
    "Eveland Dryad | (Link-1, Link/Effect, EARTH/Plant)",
    "Eveland Nymph | (Link-2, Link/Effect, EARTH/Plant)",
    "Eveland of Wants | (Link-4, Link/Effect, DARK/Plant)",
    "Receiver of Wants | (Link-3, Link/Effect, DARK/Fiend)",
    "Restrainer of Wants | (Link-1, Link/Effect, DARK/Fiend)",
    "Recurring Nightmare | (Normal Spell)",
    "Pot of Desires | (Normal Spell)",
    "Knightmare Phoenix | (Link-2, Link/Effect, FIRE/Fiend)",
    "Knightmare Unicorn | (Link-3, Link/Effect, DARK/Fiend)",
    "Monster Reborn | (Normal Spell)",
    "Torrential Tribute | (Normal Trap)",
    "Mystical Space Typhoon | (Quick-Play Spell)",
    "Allure of Darkness | (Normal Spell)",
    "Naturia Beast | (Level 5, Synchro/Effect, EARTH/Beast)",
    "Naturia Barkion | (Level 6, Synchro/Effect, EARTH/Dragon)",
    "Darklord Zerato | (Level 8, Effect, DARK/Fairy)",
    "Lonefire Blossom | (Level 3, Effect, FIRE/Plant)",
    "Dark Eruption | (Normal Spell)",
    "Destruct Potion | (Normal Trap)",
    "Surface | (Normal Spell)",
    "Necro Fusion | (Normal Trap)",
    "Underclock Taker | (Link-2, Link/Effect, DARK/Cyberse)",
    "Re-Fusion | (Normal Spell)",
    "Pot of Avarice | (Normal Spell)",
    "Poseidon Wave | (Normal Trap)"],


#INOA contains the "Raidge Clan", "Darkwood", and "Hount" archtypes.
    "INOA": ["Raidge Clan Amazoness | (Level 4, Effect, FIRE/Warrior)", 
    "Raidge Clan Berserker | (Level 4, Effect, FIRE/Warrior)",
    "Raidge Clan Crusher | (Level 4, Effect, FIRE/Warrior)",
    "Raidge Clan Harrower | (Level 4, Effect, FIRE/Warrior)",
    "Raidge Clan Khal | (Level 7, Effect, FIRE/Warrior)",
    "Boiling Blood | (Normal Spell)",
    "Raidge Clan Beserking | (Quick-Play Spell)",
    "Raidge Clan Blind Hatred | (Field Spell)",
    "Raidge Clan Looting | (Cont. Spell)",
    "Raidge Clan Tenacity | (Quick-Play Spell)",
    "Raidge Clan Warmongering | (Quick-Play Spell)",
    "Raidge Clan Brutalizer | (Rank 4, Xyz/Effect, FIRE/Warrior)",
    "Raidge Clan Veteran | (Rank 4, Xyz/Effect, FIRE/Warrior)",
    "Raidge Clan Fury | (Link-1, Link/Effect, FIRE/Warrior)",
    "Raidge Clan Smasher | (Link-2, Link/Effect, FIRE/Warrior)",
    "Raidge Clan Warlord | (Link-4, Link/Effect, FIRE/Warrior)",
    "Hount of Moonlight | (Level 4, Effect, EARTH/Zombie)",
    "Hount of Opal | (Level 4, Effect, EARTH/Zombie)",
    "Hount of the Third Knock | (Level 4, Effect, WATER/Zombie)",
    "Hount of Halley | (Level 4, Effect, WATER/Zombie)",
    "Hount of Shortfinger | (Level 4, Effect, WIND/Zombie)",
    "Hount of Doppelgänger | (Level 4, Effect, WIND/Zombie)",
    "Hount Eclipse | (Cont. Spell)",
    "Hount Howling | (Normal Spell)",
    "Hount Pack of Misfortune | (Cont. Spell)",
    "Hounted Village of Ill Omens | (Field Spell)",
    "Hounting Superstitions | (Cont. Trap)",
    "Hount of Broken Time | (Level 4, Fusion/Effect, FIRE/Zombie)",
    "Hount of the Crows | (Level 4, Fusion/Effect, FIRE/Zombie)",
    "Hount of Longtail | (Rank 4, Xyz/Effect, DARK/Zombie)",
    "Hount of Scissors | (Rank 4, Xyz/Effect, DARK/Zombie)",
    "Hount of Broken Mirror | (Link-1, Link/Effect, LIGHT/Zombie)",
    "Hount of the Thirteenth Friday | (Link-2, Link/Effect, LIGHT/Zombie)",
    "Darkwood Direwolf | (Level 4, Effect, DARK/Beast)",
    "Darkwood Eyes of the Woods | (Level 2, Tuner/Effect, DARK/Fairy)",
    "Darkwood King of the Woods | (Level 7, Effect, DARK/Dinosaur)",
    "Darkwood Satyr | (Level 4, Effect, DARK/Beast-Warrior)",
    "Darkwood Singer of Cosmic Horrors | (Level 4, Tuner/Effect, DARK/Spellcaster)",
    "Darkwood Spidertoad | (Level 4, Effect, DARK/Insect)",
    "Darkwood Spriggan | (Level 3, Tuner/Effect, DARK/Plant)",
    "Darkwood Wendigo | (Level 5, Effect, DARK/Fiend)",
    "Darkwood | (Field Spell)",
    "Darkwood Felries | (Equip Spell)",
    "Darkwood Heritage of the Swampswarm | (Equip Spell)",
    "Darkwood Scent of Blood | (Quick-Play Spell)",
    "Darkwood Stalking | (Normal Spell)",
    "Darkwood Heritage of the Vurko | (Cont. Trap)",
    "Malicious Spirits of Darkwood | (Normal Trap)",
    "Darkwood Age of Winter | (Level 10, Fusion/Effect, DARK/Psychic)",
    "Darkwood Berserker | (Level 8, Fusion/Effect, DARK/Fiend)",
    "Darkwood Treant Tyrant | (Level 8, Fusion/Effect, DARK/Zombie)",
    "Elder Entity of Darkwood - Shavath | (Level 6, Fusion/Effect, DARK/Spellcaster)",
    "Vengeful Spirit of Darkwood | (Level 5, Fusion/Effect, DARK/Zombie)",
    "Darkwood Lamia Sisters | (Link-2, Link/Tuner/Effect, DARK/Reptile)",
    "Darkwood Predator | (Link-1, Link/Effect, DARK/Rock)",
    "Darkwood Whisper of Evil | (Link-1, Link/Tuner/Effect, DARK/Warrior)",
    "Half Shut | (Quick-Play Spell)",
    "Call of the Haunted | (Normal Trap)",
    "Vampire Fraulein | (Level 5, Effect, DARK/Zombie)",
    "Vampire Sucker | (Link-2, Link/Effect, DARK/Zombie)",
    "Everliving Underworld Cannon | (Cont. Spell)",
    "Evenly Matched | (Normal Trap)",
    "Polymerization | (Normal Spell)",
    "Fusion Recovery | (Normal Spell)",
    "Lost in the Malicious Forest | (Normal Spell)",
    "Stardust Charge Warrior | (Level 6, Synchro/Effect, WIND/Warrior)",
    "Amphibious Swarmship Amblowhale | (Link-4, Link/Effect, FIRE/Machine)",
    "Blue Flame Swordsman | (Level 4, Effect, FIRE/Warrior)",
    "Salamangreat Sunlight Wolf | (Link-2, Link/Effect, FIRE/Cyberse)",
    "Ojama Trio | (Normal Trap)",
    "Malice in the Dark Woods | (Counter Trap)",
    "Tormented Mass | (Link-2, Link/Effect, DARK/Zombie)"
    ],


# KOV contains the "King of Violence" mini-series.
    "KOV": ["Eye Sage King of Violence | (Level 6, Effect, DARK/Psychic)",
    "Possessed Cannibal | (Level 4, Effect, DARK/Fiend)",
    "Allmity Decree of the King of Violence | (Level 4, Pendulum/Effect, DARK/Insect)",
    "Malifested King of Violence | (Level 8, Ritual/Effect, DARK/Fiend)",
    "Endless Hunger of the King of Violence | (Equip Spell)",
    "Haunting Vision of the King of Violence | (Equip Spell)",
    "Malifestation of the Eternal Berserk | (Ritual Spell)",
    "Malicious Aura of the King of Violence | (Cont. Trap)",
    "No Escape from the King of Violence | (Counter Trap)",
    "Darkwood Berserker | (Level 8, Fusion/Effect, DARK/Fiend)"
    ],


# TWCO Contains the "Arachnophobia" and "Allmity" archetypes.
    "TWCO": ["Arachnophobia Feeder | (Level 4, Effect, EARTH/Insect)",
    "Arachnophobia Matron | (Level 4, Effect, EARTH/Insect)",
    "Arachnophobia Praetorian | (Level 4, Effect, EARTH/Insect)",
    "Arachnophobia Weaver | (Level 4, Effect, EARTH/Insect)",
    "Arachnophobia Web Spinner |(Level 4, Effect, EARTH/Insect)",
    "Arachnophobia | (Quick-Play Spell)",
    "Dark Spinner's Web of Horror | (Field Spell)",
    "Dark Spinner's Web of Lies | (Normal Spell)",
    "Arachnophobia Sticky Nightmare | (Cont. Trap)",
    "Old Entity of Arachnophobia - Atlas-Nach | (Level 8, Synchro/Effect, DARK/Insect)",
    "Arachnophobia Brood | (Link-1, Link/Effect, DARK/Insect)",
    "Arachnophobia Web of Fate | (Link-2, Link/Effect, DARK/Insect)",
    "Allmity Clerky | (Level 5, Pendulum/Effect, LIGHT/Insect)",
    "Allmity Prosecutor | (Level 4, Pendulum/Effect, LIGHT/Insect)",
    "Allmity Witness | (Level 4, Pendulum/Effect, LIGHT/Insect)",
    "Allmity Defender | (Level 5, Pendulum/Effect, LIGHT/Insect)",
    "Allmity Judge | (Level 6, Pendulum/Effect, LIGHT/Insect)",
    "Allmity Senate | (Level 6, Pendulum/Effect, LIGHT/Insect)",
    "Allmity Guilt | (Cont. Spell)",
    "Allmity Innocence | (Cont. Spell)",
    "Court of the Allmity | (Field Spell)",
    "Allmity Order | (Normal Trap)",
    "Allmity Verdict | (Counter Trap)",
    "Allmity Decree of the King of Violence | (Level 4, Pendulum/Effect, DARK/Insect)",
    "Lawyer of All Mites | (Level 4, Pendulum/Effect, LIGHT/Insect)",
    "Allmity Injury | (Link-1, Link/Effect, LIGHT/Insect)",
    "Allmity Lawmaker | (Link-2, Link/Effect, LIGHT/Insect)",
    "Allmity Supreme | (Link-3, Link/Effect, LIGHT/Insect)",
    "Lair Wire | (Normal Trap)",
    "Spider Egg | (Normal Trap)",
    "Verdant Sanctuary | (Cont. Spell)",
    "Corrosive Scales | (Normal Trap)",
    "Gokipole | (Level 3, Effect, EARTH/Insect)",
    "Inzektor Picofalena | (Link-2, Link/Effect, DARK/Insect)",
    "Child of Silk | (Rank 4, Xyz/Effect, FIRE/Insect)",
    "Mother of Silk | (Rank 6, Xyz/Effect, FIRE/Insect)",
    "Seraphim Papillion | (Link-3, Link/Effect, WIND/Insect)",
    "Zikra, the Moth Queen | (Level 8, Synchro/Effect, WIND/Insect)",
    "Law of the Jungle | (Normal Trap)",
    "Spriggan's Deal | (Cont. Trap)",
    "Weremosquitto | (Level 4, Effect, DARK/Insect)",
    "Compulsory Evacuation Device | (Normal Trap)",
    "Pendulum Switch | (Cont. Trap)",
    "Reality Breaker | (Level 6, Effect, LIGHT/Psychic)",
    "Sacred Ritual of Desecration | (Cont. Spell)",
    "White Spider's Wedding | (Normal Trap)",
    "Silky Web of Beauty | (Link-4, Link/Effect, DARK/Insect)",
    ],

    "": ["",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",]
}




STR_ID_List = {
    "ITDW": [
    # Main Deck Monsters
    "Darkwood Direwolf | (Level 4, Effect, DARK/Beast)",
    "Darkwood Direwolf | (Level 4, Effect, DARK/Beast)",
    "Darkwood Eyes of the Woods | (Level 2, Tuner/Effect, DARK/Fairy)",
    "Darkwood Eyes of the Woods | (Level 2, Tuner/Effect, DARK/Fairy)",
    "Darkwood King of the Woods | (Level 7, Effect, DARK/Dinosaur)",
    "Darkwood King of the Woods | (Level 7, Effect, DARK/Dinosaur)",
    "Darkwood Satyr | (Level 4, Effect, DARK/Beast-Warrior)",
    "Darkwood Satyr | (Level 4, Effect, DARK/Beast-Warrior)",
    "Darkwood Singer of Cosmic Horrors | (Level 4, Tuner/Effect, DARK/Spellcaster)",
    "Darkwood Singer of Cosmic Horrors | (Level 4, Tuner/Effect, DARK/Spellcaster)",
    "Darkwood Spidertoad | (Level 4, Effect, DARK/Insect)",
    "Darkwood Spidertoad | (Level 4, Effect, DARK/Insect)",
    "Darkwood Spriggan | (Level 3, Tuner/Effect, DARK/Plant)",
    "Darkwood Spriggan | (Level 3, Tuner/Effect, DARK/Plant)",
    "Darkwood Wendigo | (Level 5, Effect, DARK/Fiend)",
    "Darkwood Wendigo | (Level 5, Effect, DARK/Fiend)",

    # Spells
    "Darkwood | (Field Spell)",
    "Darkwood Felries | (Equip Spell)",
    "Darkwood Heritage of the Swampswarm | (Equip Spell)",
    "Darkwood Scent of Blood | (Quick-Play Spell)",
    "Darkwood Stalking | (Normal Spell)",
    "Half Shut | (Quick-Play Spell)",
    "Polymerization | (Normal Spell)",
    "Polymerization | (Normal Spell)",
    "Fusion Recovery | (Normal Spell)",
    "Fusion Sage | (Normal Spell)",
    "Monster Reborn | (Normal Spell)",
    "Lost in the Malicious Forest | (Normal Spell)",
    "Twin Twister | (Quick-Play Spell)",
    "Mystical Space Typhoon | (Quick-Play Spell)",
    "Haunting Vision of the King of Violence | (Equip Spell)",
    "Endless Hunger of the King of Violence | (Equip Spell)",
    "Card Rotator | (Normal Spell)",
    "Terraforming | (Normal Spell)",

    # Traps
    "Ojama Trio | (Normal Trap)",
    "Darkwood Heritage of the Vurko | (Cont. Trap)",
    "Malicious Spirits of Darkwood | (Normal Trap)",
    "Malicious Aura of the King of Violence | (Cont. Trap)",
    "No Escape from the King of Violence | (Counter Trap)",
    "Evenly Matched | (Normal Trap)",

    # Extra Deck Monsters
    "Darkwood Age of Winter | (Level 10, Fusion/Effect, DARK/Psychic)",
    "Darkwood Berserker | (Level 8, Fusion/Effect, DARK/Fiend)",
    "Darkwood Treant Tyrant | (Level 8, Fusion/Effect, DARK/Zombie)",
    "Vengeful Spirit of Darkwood | (Level 5, Fusion/Effect, DARK/Zombie)",
    "Darkwood Predator | (Link-1, Link/Effect, DARK/Rock)",
    "Darkwood Whisper of Evil | (Link-1, Link/Effect, DARK/Warrior)"
    ],


    "UAPG": ["U.A. Midfielder | (Level 4, Effect, EARTH/Warrior)",
    "U.A. Libero Spiker | (Level 4, Effect, EARTH/Warrior)",
    "U.A. Blockbacker | (Level 7, Effect, EARTH/Warrior)",
    "U.A. Playmaker | (Level 8, Effect, EARTH/Warrior)",
    "U.A. Goalkeeper | (Level 6, Effect, EARTH/Warrior)",
    "U.A. Mighty Slugger | (Level 5, Effect, EARTH/Warrior)",
    "U.A. Perfect Ace | (Level 5, Effect, EARTH/Warrior)",
    "U.A. Player Manager | (Level 8, Effect, EARTH/Warrior)",
    "U.A. Dreadnought Dunker | (Level 7, Effect, EARTH/Warrior)",
    "U.A. Rival Rebounder | (Level 6, Effect, EARTH/Warrior)",
    "Lava Golem | (Level 8, Effect, FIRE/Fiend)",
    "D.D. Crow | (Level 1, Effect, DARK/Winged Beast)",
    "Ghost Sister & Spooky Dogwood | (Level 3, Tuner/Effect, WATER/Zombie)",
    "Effect Veiler | (Level 1, Tuner/Effect, LIGHT/Fairy)",
    "Ghost Belle & Haunted Mansion | (Level 3, Tuner/Effect, EARTH/Zombie)",
    "Marauding Captain | (Level 3, Effect, EARTH/Warrior)",
    "Skull Meister | (Level 4, Effect, DARK/Fiend)",
    "Scapegoat | (Quick-Play Spell)",
    "Reinforcements of the Army | (Normal Spell)",
    "Foolish Burial Goods | (Normal Spell)",
    "Mind Control | (Normal Spell)",
    "Pot of Avarice | (Normal Spell)"
    "Living Fossil | (Equip Spell)",
    "Monster Reborn | (Normal Spell)",
    "Twin Twister | (Quick-Play Spell)",
    "Terraforming | (Normal Spell)",
    "Mystical Space Typhoon | (Quick-Play Spell)",
    "U.A. Signing Deal | (Normal Spell)",
    "U.A. Locker Room | (Quick-Play Spell)",
    "U.A. Turnover Tactics | (Quick-Play Spell)",
    "U.A. Stadium | (Field Spell)",
    "U.A. Hyper Stadium | (Field Spell)",
    "U.A. Power Jersey | (Equip Spell)",
    "U.A. Man of the Match | (Normal Trap)",
    "U.A. Penalty Box | (Cont. Trap)",
    "Lost Wind | (Normal Trap)",
    "Unending Nightmare | (Cont. Trap)",
    "Titancider | (Normal Trap)",
    "Gozen Match | (Cont. Trap)",
    "Imperial Iron Wall | (Cont. Trap)",
],
    
}
# 40









